# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/ug24/2403323/Downloads/Bit-Torrent-Lite-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/ug24/2403323/Downloads/Bit-Torrent-Lite-main/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/ug24/2403323/Downloads/Bit-Torrent-Lite-main/build/CMakeFiles /users/ug24/2403323/Downloads/Bit-Torrent-Lite-main/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/ug24/2403323/Downloads/Bit-Torrent-Lite-main/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BitTorrentClient

# Build rule for target.
BitTorrentClient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BitTorrentClient
.PHONY : BitTorrentClient

# fast build rule for target.
BitTorrentClient/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/build
.PHONY : BitTorrentClient/fast

src/leecher/leecher.o: src/leecher/leecher.cpp.o
.PHONY : src/leecher/leecher.o

# target to build an object file
src/leecher/leecher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/leecher/leecher.cpp.o
.PHONY : src/leecher/leecher.cpp.o

src/leecher/leecher.i: src/leecher/leecher.cpp.i
.PHONY : src/leecher/leecher.i

# target to preprocess a source file
src/leecher/leecher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/leecher/leecher.cpp.i
.PHONY : src/leecher/leecher.cpp.i

src/leecher/leecher.s: src/leecher/leecher.cpp.s
.PHONY : src/leecher/leecher.s

# target to generate assembly for a file
src/leecher/leecher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/leecher/leecher.cpp.s
.PHONY : src/leecher/leecher.cpp.s

src/listener/listener.o: src/listener/listener.cpp.o
.PHONY : src/listener/listener.o

# target to build an object file
src/listener/listener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/listener/listener.cpp.o
.PHONY : src/listener/listener.cpp.o

src/listener/listener.i: src/listener/listener.cpp.i
.PHONY : src/listener/listener.i

# target to preprocess a source file
src/listener/listener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/listener/listener.cpp.i
.PHONY : src/listener/listener.cpp.i

src/listener/listener.s: src/listener/listener.cpp.s
.PHONY : src/listener/listener.s

# target to generate assembly for a file
src/listener/listener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/listener/listener.cpp.s
.PHONY : src/listener/listener.cpp.s

src/lpd/lpd.o: src/lpd/lpd.cpp.o
.PHONY : src/lpd/lpd.o

# target to build an object file
src/lpd/lpd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/lpd/lpd.cpp.o
.PHONY : src/lpd/lpd.cpp.o

src/lpd/lpd.i: src/lpd/lpd.cpp.i
.PHONY : src/lpd/lpd.i

# target to preprocess a source file
src/lpd/lpd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/lpd/lpd.cpp.i
.PHONY : src/lpd/lpd.cpp.i

src/lpd/lpd.s: src/lpd/lpd.cpp.s
.PHONY : src/lpd/lpd.s

# target to generate assembly for a file
src/lpd/lpd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/lpd/lpd.cpp.s
.PHONY : src/lpd/lpd.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser/decoder.o: src/parser/decoder.cpp.o
.PHONY : src/parser/decoder.o

# target to build an object file
src/parser/decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/parser/decoder.cpp.o
.PHONY : src/parser/decoder.cpp.o

src/parser/decoder.i: src/parser/decoder.cpp.i
.PHONY : src/parser/decoder.i

# target to preprocess a source file
src/parser/decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/parser/decoder.cpp.i
.PHONY : src/parser/decoder.cpp.i

src/parser/decoder.s: src/parser/decoder.cpp.s
.PHONY : src/parser/decoder.s

# target to generate assembly for a file
src/parser/decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/parser/decoder.cpp.s
.PHONY : src/parser/decoder.cpp.s

src/peer/peer.o: src/peer/peer.cpp.o
.PHONY : src/peer/peer.o

# target to build an object file
src/peer/peer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer.cpp.o
.PHONY : src/peer/peer.cpp.o

src/peer/peer.i: src/peer/peer.cpp.i
.PHONY : src/peer/peer.i

# target to preprocess a source file
src/peer/peer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer.cpp.i
.PHONY : src/peer/peer.cpp.i

src/peer/peer.s: src/peer/peer.cpp.s
.PHONY : src/peer/peer.s

# target to generate assembly for a file
src/peer/peer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer.cpp.s
.PHONY : src/peer/peer.cpp.s

src/peer/peer_handshake.o: src/peer/peer_handshake.cpp.o
.PHONY : src/peer/peer_handshake.o

# target to build an object file
src/peer/peer_handshake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer_handshake.cpp.o
.PHONY : src/peer/peer_handshake.cpp.o

src/peer/peer_handshake.i: src/peer/peer_handshake.cpp.i
.PHONY : src/peer/peer_handshake.i

# target to preprocess a source file
src/peer/peer_handshake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer_handshake.cpp.i
.PHONY : src/peer/peer_handshake.cpp.i

src/peer/peer_handshake.s: src/peer/peer_handshake.cpp.s
.PHONY : src/peer/peer_handshake.s

# target to generate assembly for a file
src/peer/peer_handshake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer_handshake.cpp.s
.PHONY : src/peer/peer_handshake.cpp.s

src/peer/peer_messaging.o: src/peer/peer_messaging.cpp.o
.PHONY : src/peer/peer_messaging.o

# target to build an object file
src/peer/peer_messaging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer_messaging.cpp.o
.PHONY : src/peer/peer_messaging.cpp.o

src/peer/peer_messaging.i: src/peer/peer_messaging.cpp.i
.PHONY : src/peer/peer_messaging.i

# target to preprocess a source file
src/peer/peer_messaging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer_messaging.cpp.i
.PHONY : src/peer/peer_messaging.cpp.i

src/peer/peer_messaging.s: src/peer/peer_messaging.cpp.s
.PHONY : src/peer/peer_messaging.s

# target to generate assembly for a file
src/peer/peer_messaging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/peer/peer_messaging.cpp.s
.PHONY : src/peer/peer_messaging.cpp.s

src/requestor/requestor.o: src/requestor/requestor.cpp.o
.PHONY : src/requestor/requestor.o

# target to build an object file
src/requestor/requestor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/requestor/requestor.cpp.o
.PHONY : src/requestor/requestor.cpp.o

src/requestor/requestor.i: src/requestor/requestor.cpp.i
.PHONY : src/requestor/requestor.i

# target to preprocess a source file
src/requestor/requestor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/requestor/requestor.cpp.i
.PHONY : src/requestor/requestor.cpp.i

src/requestor/requestor.s: src/requestor/requestor.cpp.s
.PHONY : src/requestor/requestor.s

# target to generate assembly for a file
src/requestor/requestor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/requestor/requestor.cpp.s
.PHONY : src/requestor/requestor.cpp.s

src/seeder/seeder.o: src/seeder/seeder.cpp.o
.PHONY : src/seeder/seeder.o

# target to build an object file
src/seeder/seeder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/seeder/seeder.cpp.o
.PHONY : src/seeder/seeder.cpp.o

src/seeder/seeder.i: src/seeder/seeder.cpp.i
.PHONY : src/seeder/seeder.i

# target to preprocess a source file
src/seeder/seeder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/seeder/seeder.cpp.i
.PHONY : src/seeder/seeder.cpp.i

src/seeder/seeder.s: src/seeder/seeder.cpp.s
.PHONY : src/seeder/seeder.s

# target to generate assembly for a file
src/seeder/seeder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/seeder/seeder.cpp.s
.PHONY : src/seeder/seeder.cpp.s

src/utils/hasher.o: src/utils/hasher.cpp.o
.PHONY : src/utils/hasher.o

# target to build an object file
src/utils/hasher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/hasher.cpp.o
.PHONY : src/utils/hasher.cpp.o

src/utils/hasher.i: src/utils/hasher.cpp.i
.PHONY : src/utils/hasher.i

# target to preprocess a source file
src/utils/hasher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/hasher.cpp.i
.PHONY : src/utils/hasher.cpp.i

src/utils/hasher.s: src/utils/hasher.cpp.s
.PHONY : src/utils/hasher.s

# target to generate assembly for a file
src/utils/hasher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/hasher.cpp.s
.PHONY : src/utils/hasher.cpp.s

src/utils/helper.o: src/utils/helper.cpp.o
.PHONY : src/utils/helper.o

# target to build an object file
src/utils/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/helper.cpp.o
.PHONY : src/utils/helper.cpp.o

src/utils/helper.i: src/utils/helper.cpp.i
.PHONY : src/utils/helper.i

# target to preprocess a source file
src/utils/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/helper.cpp.i
.PHONY : src/utils/helper.cpp.i

src/utils/helper.s: src/utils/helper.cpp.s
.PHONY : src/utils/helper.s

# target to generate assembly for a file
src/utils/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/helper.cpp.s
.PHONY : src/utils/helper.cpp.s

src/utils/socket_utils.o: src/utils/socket_utils.cpp.o
.PHONY : src/utils/socket_utils.o

# target to build an object file
src/utils/socket_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/socket_utils.cpp.o
.PHONY : src/utils/socket_utils.cpp.o

src/utils/socket_utils.i: src/utils/socket_utils.cpp.i
.PHONY : src/utils/socket_utils.i

# target to preprocess a source file
src/utils/socket_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/socket_utils.cpp.i
.PHONY : src/utils/socket_utils.cpp.i

src/utils/socket_utils.s: src/utils/socket_utils.cpp.s
.PHONY : src/utils/socket_utils.s

# target to generate assembly for a file
src/utils/socket_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BitTorrentClient.dir/build.make CMakeFiles/BitTorrentClient.dir/src/utils/socket_utils.cpp.s
.PHONY : src/utils/socket_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BitTorrentClient"
	@echo "... src/leecher/leecher.o"
	@echo "... src/leecher/leecher.i"
	@echo "... src/leecher/leecher.s"
	@echo "... src/listener/listener.o"
	@echo "... src/listener/listener.i"
	@echo "... src/listener/listener.s"
	@echo "... src/lpd/lpd.o"
	@echo "... src/lpd/lpd.i"
	@echo "... src/lpd/lpd.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser/decoder.o"
	@echo "... src/parser/decoder.i"
	@echo "... src/parser/decoder.s"
	@echo "... src/peer/peer.o"
	@echo "... src/peer/peer.i"
	@echo "... src/peer/peer.s"
	@echo "... src/peer/peer_handshake.o"
	@echo "... src/peer/peer_handshake.i"
	@echo "... src/peer/peer_handshake.s"
	@echo "... src/peer/peer_messaging.o"
	@echo "... src/peer/peer_messaging.i"
	@echo "... src/peer/peer_messaging.s"
	@echo "... src/requestor/requestor.o"
	@echo "... src/requestor/requestor.i"
	@echo "... src/requestor/requestor.s"
	@echo "... src/seeder/seeder.o"
	@echo "... src/seeder/seeder.i"
	@echo "... src/seeder/seeder.s"
	@echo "... src/utils/hasher.o"
	@echo "... src/utils/hasher.i"
	@echo "... src/utils/hasher.s"
	@echo "... src/utils/helper.o"
	@echo "... src/utils/helper.i"
	@echo "... src/utils/helper.s"
	@echo "... src/utils/socket_utils.o"
	@echo "... src/utils/socket_utils.i"
	@echo "... src/utils/socket_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

